title: "ATL BIM & CAD Standards"
description: "Version-controlled standards for CAD and BIM at ATL."
theme: "just-the-docs"
remote_theme: just-the-docs/just-the-docs
color_scheme: "light"

# Enable for clean sidebar nav
collections:
  cad:
    output: true
    permalink: /cad/:path/
  bim:
    output: true
    permalink: /bim/:path/

just_the_docs:
  collections:
    cad:
      name: "CAD Standards"
      nav_exclude: false
    bim:
      name: "BIM Standards"
      nav_exclude: false

url: "https://bim.atlstandards.com"
