name: Build and Deploy to Bluehost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build the Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to Bluehost via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: atlstandards.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          server-dir: /public_html/bim/
          local-dir: ./_site/
          log-level: verbose
